/** AUTH **/
export const LOGIN_ATTEMP = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const LOGIN_ATTEMP_FACEBOOK = 'LOGIN_ATTEMPT_FACEBOOK';
export const LOGIN_ATTEMP_GOOGLE = 'LOGIN_ATTEMP_GOOGLE';
export const LOGIN_ATTEMP_TWITTER = 'LOGIN_ATTEMP_TWITTER';

export const RESET_PASSWORD_ATTEMP = 'RESET_PASSWORD_ATTEMP';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const REGISTER_ATTEMP = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

/** USER **/
export const USER_READ = 'USER_READ';
export const USER_READ_SUCCESS = 'USER_READ_SUCCESS';
export const USER_READ_FAILURE = 'USER_READ_FAILURE';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR= 'USER_UPDATE_ERROR';

/** ABOUT US**/
export const ABOUT_READ = "ABOUT_READ";
export const ABOUT_SAVE = "ABOUT_SAVE";

// SERVICES ACTIONS
export const RECEIVE_SERVICES_DATA= "RECEIVE_SERVICES_DATA";
export const AWAIT_NEW_SERVICE_RESPONSE= "AWAIT_NEW_SERVICE_RESPONSE";
export const RECEIVE_NEW_SERVICE_RESPONSE= "RECEIVE_NEW_SERVICE_RESPONSE";
export const START_SERVICE_EDIT= "START_SERVICE_EDIT";
export const FINISH_SERVICE_EDIT= "FINISH_SERVICE_EDIT";
export const SUBMIT_SERVICE_EDIT= "SUBMIT_SERVICE_EDIT";

// SERVICES STATES
export const EDITING_SERVICE= "EDITING_SERVICE";
export const SUBMITTING_SERVICE= "SUBMITTING_SERVICE";

export const DISPLAY_ERROR = "DISPLAY_ERROR";
export const DISPLAY_MESSAGE = "DISPLAY_MESSAGE";
export const DISMISS_FEEDBACK = "DISMISS_FEEDBACK";

// VEHICLES ACTIONS
export const RECEIVE_VEHICLES_DATA= "RECEIVE_VEHICLES_DATA";
export const AWAIT_NEW_VEHICLE_RESPONSE= "AWAIT_NEW_VEHICLE_RESPONSE";
export const RECEIVE_NEW_VEHICLE_RESPONSE= "RECEIVE_NEW_VEHICLE_RESPONSE";
export const START_VEHICLE_EDIT= "START_VEHICLE_EDIT";
export const FINISH_VEHICLE_EDIT= "FINISH_VEHICLE_EDIT";
export const SUBMIT_VEHICLE_EDIT= "SUBMIT_VEHICLE_EDIT";

// VEHICLES STATES
export const EDITING_VEHICLE= "EDITING_VEHICLE";
export const SUBMITTING_VEHICLE= "SUBMITTING_VEHICLE";
